import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'todo-input',
  template: `
      <!--<p>The title is: {{ title }}</p>-->
      <!-- <input [value]="title">-->
       <!--- <input value={{title}}> --->
      <input  class="todo-input" [value]="title" 
             (keyup.enter)="changeTitle(inputElement)"#inputElement>
             <!--(keyup.enter)="changeTitle($event.target.value)"#inputElement>-->
             <!--(keyup.enter)="changeTitle($event)"> -->
             <!-- (keyup)="changeTitle($event.target.value)"> 
             <!-- (keyup)="changeTitle('Button Clicked!')"> -->
            <!--<button (click)="changeTitle('Button Clicked!')">Save</button> -->
       <!--<button (click)="changeTitle(inputElement.value)">Save</button>-->
      <button class="btn"  (click)="changeTitle(inputElement)">Save</button>      
  `,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {
  title: string = "Orit";
  @Output() submitValue: EventEmitter<string> = new EventEmitter();

  // generateTitle(): string {
  //   return 'This title was generated by a method.';
  // }
  //   changeTitle(event): void {
  //   console.log(event);
  //   this.title = event.target.value; // the original functionality still works
  // }
  // changeTitle(inputElementReference): void {
  //   console.log(inputElementReference);
  //   this.title = inputElementReference.value;
  // }

  changeTitle(newTitle): void {
    this.submitValue.emit(newTitle.value);
  }
  // changeTitle(newTitle: string): void {
  //   this.title = newTitle;
  // }
  // changeTitle(newTitle: string): string {
  //   this.title = newTitle;
  //   return this.title;
  // }
  constructor() {
    // this.title = 'Hello World';
    // this.changeTitle('I love Angular');
    // console.log("in cinstructor  " + this.title);
  }

  ngOnInit() {
    // this.title = "changing from oninit";
    // this.changeTitle('hate Angular');
    //   setTimeout(() => {
    //   this.title = 'This is not the title you are looking for';  
    // }, 3000);
    // this.generateTitle();
  }
}
